---
name: find-artifact-by-ref

description: Find a workflow artifact for a particular ref

inputs:
  ref:
    description: Only search workflows on this git ref
    required: true
  artifact-name:
    description: Only match artifacts with this name
    required: true
  check-name:
    description: Only search workflows that contain a matching check name
    required: false
  download:
    description: If set, will download the matched artifact
    required: false
    default: 'false'
  github-token:
    description: The GitHub token used to create an authenticated client
    required: false
    default: ${{ github.token }}

outputs:
  artifact-id:
    description: The artifact ID of the found artifact

runs:
  using: node16
  main: out.js
