---
name: actions-find-artifact-by-ref

description: Find a workflow artifact for a particular ref

inputs:
  ref:
    description: Only search workflows on this git ref
    required: true
  artifact_name:
    description: Only match artifacts with this name
    required: true
  download:
    description: If set, will download the matched artifact
    required: false
    default: 'false'
  github_token:
    description: The GitHub token used to create an authenticated client
    required: false
    default: ${{ github.token }}
  run_name:
    description: |
      The name of the run that generated the artifact. This can help narrow the
      number of workflow runs that are considered, reducing the chance of
      artifact name collisions and reducing the number of necessary API calls.
      If not provided, all workflow runs for the provided ref will be considered
    required: false
    default: ''

outputs:
  error:
    description: An error code if the action fails (mostly for testing)
  artifact_id:
    description: The artifact ID of the found artifact

runs:
  using: node20
  main: out.js
