---
name: find-artifact-by-ref

description: Find a workflow artifact for a particular ref

inputs:
  ref:
    description: Only search workflows on this git ref
    required: true
  artifact_name:
    description: Only match artifacts with this name
    required: true
  check_name:
    description: Only search workflows that contain a matching check name
    required: false
  download:
    description: If set, will download the matched artifact
    required: false
    default: 'false'
  github_token:
    description: The GitHub token used to create an authenticated client
    required: false
    default: ${{ github.token }}

outputs:
  error:
    description: An error code if the action fails (mostly for testing)
  artifact_id:
    description: The artifact ID of the found artifact

runs:
  using: node16
  main: out.js
